name: Build
run-name: ${{ github.event.head_commit.message }}
 🚀
on: 
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - 'main'
  push:
    branches:
      - 'main'

jobs:
  build:
    strategy:
      matrix:
        java-version: [ 8, 11, 17, 21 ]
        include:
          - java-version: 17
            dep-path: true
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java-version }}
        cache: maven
    - name: Test with Maven
      run: mvn --batch-mode --update-snapshots verify

    - if: ${{ matrix.dep-path }}
      name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6

  deploy-snapshot:
    if: github.event_name == 'push' && github.ref_name == 'main'
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        server-id: timeular.oss.sonatype.org
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD

    - name: Build with Maven
      run: mvn --batch-mode package

    - name: Publish snapshot
      run: mvn --batch-mode deploy
      env:
        MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.OSSRH_PWD }}
